name: Tests
on:
  pull_request:
  push:
    branches:
    - master
  schedule:
    # Weekly.
    - cron: "0 0 * * 0"

jobs:
  track-config:
    name: Check track configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch
        run: bin/fetch-configlet

      - name: Lint
        run: bin/configlet lint --track-id zig .

      - name: Check for invalid UUIDs
        # can be removed once `configlet lint` gains this ability.
        # Check issue https://github.com/exercism/configlet/issues/99
        run: |
          uuids=$(jq --raw-output '.exercises | map(.uuid) | .[]' config.json)
          bad_uuid=$(echo "$uuids" | grep -vE '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' || true)
          if [ -n "$bad_uuid" ]; then
            echo "invalid UUIDs found! please correct these to be valid UUIDs:"
            echo "$bad_uuid"
            exit 1
          fi

  exercises:
    name: Check exercises
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Zig
        run: |
          curl -o zig.tar.xz https://ziglang.org/download/0.6.0/zig-linux-x86_64-0.6.0.tar.xz
          tar xJf zig.tar.xz
          mkdir -p $HOME/bin
          ln -s $(pwd)/zig-*/zig $HOME/bin

      - name: Check exercises
        run: sh test-good-exercises.sh

  broken-exercises:
    name: Check broken exercises
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Zig
        run: |
          curl -o zig.tar.xz https://ziglang.org/download/0.6.0/zig-linux-x86_64-0.6.0.tar.xz
          tar xJf zig.tar.xz
          mkdir -p $HOME/bin
          ln -s $(pwd)/zig-*/zig $HOME/bin

      - name: Check exercises
        run: sh test-broken-exercises.sh
